### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by progre** [Skippeh/Oxide.GettingOverItMP#4]
I tried to build on Visual Studio Community 2017, but can't build with some errors.
Could you tell me how to build it?
![rapture_20180603115036](https://user-images.githubusercontent.com/1272114/40882700-c48512a6-6724-11e8-9ef9-de9945398935.png)

**Comment by Skippeh** [comment]
Can you try again? You might get different errors but i think these particular errors should be fixed. Make sure you download the submodules too and that all projects load successfully (you have 2 projects that aren't loaded in the image).

**Comment by progre** [comment]
OK. Certenly I have forgetten to clone submodule. I retry it as;
`git clone git@github.com:Skippeh/Oxide.GettingOverItMP.git --recursive`

but my build is still failed with another errors.
It looks like errors about Unity Engine.
![rapture_20180609101032](https://user-images.githubusercontent.com/1272114/41186241-3f6e25b8-6bce-11e8-9dac-487c59b73b18.png)
